export const COCTAILS = [
  {
    id: 0,
    imageSrc: 'assets/img/coctails/0.jpg',
    name: 'Gin and Tonic',
    type: ['low-alcohol', 'bitter', 'gin based', 'mixes', 'long drinks'],
    composition: [
      {
        id: 1,
        name: 'Gin',
        type: 'Spirits',
        unit: 'ml',
        amount: 50,
      },
      {
        id: 51,
        name: 'Тоник',
        type: 'Вода и напитки',
        unit: 'ml',
        amount: 150,
      },
      {
        id: 52,
        name: 'Lime',
        type: 'Fruits',
        unit: 'g',
        amount: 20,
      },
      {
        id: 53,
        name: 'Лед в кубиках',
        type: 'Ice',
        unit: 'g',
        amount: 180,
      },
    ],
    recipe: ['Fill a highball glass to the top with ice cubes',
      'Pour in 50 ml of gin',
      'Top up with tonic and stir gently',
      'Garnish with 2 lime wheels'],
    description: 'This is an immortal mix of gin and tonic, which is served in probably every bar on Earth. Herbal and slightly bitter cocktail perfectly refreshes and tones. You can decorate it with lime or cucumber, depending on what you prefer - freshness or sourness.'
  },
  {
    id: 1,
    imageSrc: 'assets/img/coctails/1.jpg',
    name: 'Blue Lagoon',
    type: ['low-alcohol', 'citrus', 'tropical', 'sweet', 'vodka based'],
    composition: [
      {
        id: 0,
        name: 'Vodka',
        type: 'Strong spirits',
        unit: 'ml',
        amount: 50,
      },
      {
        id: 28,
        name: 'Blue curacao liqueur',
        type: 'Liqueurs and Bitters',
        unit: 'ml',
        amount: 20,
      },
      {
        id: 54,
        name: 'Sprite',
        type: 'Water and drinks',
        unit: 'ml',
        amount: 150,
      },
      {
        id: 55,
        name: 'Pineapple',
        type: 'Fruits',
        unit: 'g',
        amount: 30,
      },
      {
        id: 53,
        name: 'Ice cubes',
        type: 'Ice',
        unit: 'g',
        amount: 200,
      },
    ],
    recipe: ['Fill a hurricane glass to the top with ice cubes',
      'Pour in 20 ml of blue curacao liqueur and 50 ml of vodka',
      'Top up with sprite and stir gently',
      'Garnish with a pineapple wedge'],
    description: 'This is a sweet refreshing vodka long with the addition of blue curacao liqueur, which gives the cocktail a delicate blue hue. There is a legend that the "Blue Lagoon" was invented by the artist Paul Gauguin in Tahiti, but it is unlikely that he would suggest adding a sprite to the cocktail'
  },
  {
    id: 2,
    imageSrc: 'assets/img/coctails/2.jpg',
    name: 'Aperol Spritz',
    type: ['low-alcohol', 'sweet', 'sparkling', 'simple','fizz'],
    composition: [
      {
        id: 34,
        name: 'Aperol',
        type: 'Liqueurs and Bitters',
        unit: 'ml',
        amount: 100,
      },
      {
        id: 38,
        name: 'Prosecco',
        type: 'Wines',
        unit: 'ml',
        amount: 100,
      },
      {
        id: 56,
        name: 'Club soda',
        type: 'Water and drinks',
        unit: 'ml',
        amount: 20,
      },
      {
        id: 57,
        name: 'Orange',
        type: 'Fruits',
        unit: 'g',
        amount: 40,
      },
      {
        id: 53,
        name: 'Ice cubes',
        type: 'Ice',
        unit: 'g',
        amount: 60,
      },
    ],
    recipe: ['Fill a wine glass with ice',
      'Pour in 100 ml of prosecco and 100 ml of Aperol',
      'Add a splash of club soda and mix with a bar spoon',
      'Garnish with an orange wedge'],
    description: 'Aperol Spritz is a favorite among summer season cocktails. In European resorts, it is difficult to find an institution where it is not served. The Italian (classic) version of Aperol contains 11% alcohol. The drink, made for shipments to Germany, is 4% stronger due to local legislation that requires drinks with an alcohol content of less than 15% to be bottled in refillable bottles.'
  }
]
